[tool.poetry]
name = "broker_agent"
version = "0.1.0"
description = "Your very own AI real estate search agent!"
authors = ["Gage Anderson <gage@gageanderson.io>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
