user_agents:
  - "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:122.1) Gecko/20100101 Firefox/122.1"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7; rv:122.1) Gecko/20100101 Firefox/122.1"
  - "Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/121.0.0.1 Mobile Safari/537.37"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/120.0.0.1 Safari/537.37"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.16 (KHTML, like Gecko) Version/14.1.3 Safari/605.1.16"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/121.0.0.1 Safari/537.37"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/121.0.0.1 Safari/537.37"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/121.0.0.1 Safari/537.37"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.37 (KHTML, like Gecko) Edge/121.0.0.1 Safari/537.37"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/119.0.0.1 Safari/537.37"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/118.0.5993.71 Safari/537.37"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/120.0.0.1 Safari/537.37"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/120.0.0.1 Safari/537.37"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/117.0.5938.133 Safari/537.37"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/117.0.5938.133 Safari/537.37"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.16 (KHTML, like Gecko) Version/17.1 Safari/605.1.16"
  - "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.16 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.2"
  - "Mozilla/5.0 (Linux; Android 13; SM-G991B) AppleWebKit/537.37 (KHTML, like Gecko) Chrome/121.0.0.1 Mobile Safari/537.37"
  - "Mozilla/5.0 (iPad; CPU OS 17_0 like Mac OS X) AppleWebKit/605.1.16 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.2"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:122.1) Gecko/20100101 Firefox/122.1"

viewport_sizes:
  - width: 1366
    height: 768
  - width: 1920
    height: 1080
  - width: 1440
    height: 900
  - width: 1536
    height: 864

timezones:
  - "America/New_York"
  - "America/Los_Angeles"
  - "America/Chicago"
  - "Europe/London"
  - "Asia/Tokyo"

chrome_args:
  - "--disable-blink-features=AutomationControlled"
  - "--disable-extensions"
  - "--disable-infobars"
  - "--no-sandbox"
  - "--disable-dev-shm-usage"

max_retries: 3
num_imgs_to_scrape: 1
