user_agents:
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36"
  - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Edge/121.0.0.0 Safari/537.36"

viewport_sizes:
  - width: 1366
    height: 768
  - width: 1920
    height: 1080
  - width: 1440
    height: 900
  - width: 1536
    height: 864

timezones:
  - "America/New_York"
  - "America/Los_Angeles"
  - "America/Chicago"
  - "Europe/London"
  - "Asia/Tokyo"

chrome_args:
  - "--disable-blink-features=AutomationControlled"
  - "--disable-extensions"
  - "--disable-infobars"
  - "--no-sandbox"
  - "--disable-dev-shm-usage"
