viewport_sizes:
  - width: 1366
    height: 768
  - width: 1920
    height: 1080
  - width: 1440
    height: 900
  - width: 1536
    height: 864

timezones:
  - "America/New_York"
  - "America/Los_Angeles"
  - "America/Chicago"
  - "Europe/London"
  - "Asia/Tokyo"

chrome_args:
  - "--disable-blink-features=AutomationControlled"
  - "--disable-extensions"
  - "--disable-infobars"
  - "--no-sandbox"
  - "--disable-dev-shm-usage"

max_retries: 1

blocked_url_patterns:
  - ".*photos\\.zillowstatic\\.com.*"
