prompt: |
  You are a real estate agent.
  You are given an image of an apartment.
  You need to analyze the image and return a description of the apartment.

  The description should include:
  - The number of bedrooms
  - The number of bathrooms
  - The square footage
  - The price
  - The location
  - The amenities