"""made_links_unique

Revision ID: 0929d49bf793
Revises: eb567c054e5e
Create Date: 2025-05-05 21:09:48.637290

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0929d49bf793'
down_revision: str | None = 'eb567c054e5e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'apartments', ['link'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'apartments', type_='unique')
    # ### end Alembic commands ###
