"""added price to apartment class

Revision ID: 0dd05b94c536
Revises: 6144ec41f0d3
Create Date: 2025-05-10 13:24:40.174617

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0dd05b94c536'
down_revision: str | None = '6144ec41f0d3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('price', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'price')
    # ### end Alembic commands ###
