"""added more optional fields to apartments

Revision ID: 45eb195b5d02
Revises: 84acdead0d66
Create Date: 2025-05-18 11:27:47.602258

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '45eb195b5d02'
down_revision: str | None = '84acdead0d66'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('sqft', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('num_beds', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('num_baths', sa.Integer(), nullable=True))
    op.add_column('apartments', sa.Column('neighborhood', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'neighborhood')
    op.drop_column('apartments', 'num_baths')
    op.drop_column('apartments', 'num_beds')
    op.drop_column('apartments', 'sqft')
    # ### end Alembic commands ###
