"""more_apt_listing_metadata

Revision ID: 6144ec41f0d3
Revises: 0929d49bf793
Create Date: 2025-05-05 21:34:34.521543

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6144ec41f0d3'
down_revision: str | None = '0929d49bf793'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('date_scraped', sa.DateTime(), nullable=False))
    op.add_column('apartments', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('apartments', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('apartments', sa.Column('available_date', sa.DateTime(), nullable=False))
    op.add_column('apartments', sa.Column('days_on_market', sa.Integer(), nullable=False))
    op.add_column('apartments', sa.Column('image_urls', sa.ARRAY(sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'image_urls')
    op.drop_column('apartments', 'days_on_market')
    op.drop_column('apartments', 'available_date')
    op.drop_column('apartments', 'description')
    op.drop_column('apartments', 'name')
    op.drop_column('apartments', 'date_scraped')
    # ### end Alembic commands ###
