"""added price history

Revision ID: 626177592f6d
Revises: 765360ebcbf7
Create Date: 2025-05-13 20:29:31.254890

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '626177592f6d'
down_revision: str | None = '765360ebcbf7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('price_history_id', sa.UUID(), nullable=False),
    sa.Column('apartment_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['apartment_id'], ['apartments.apartment_id'], ),
    sa.PrimaryKeyConstraint('price_history_id')
    )
    op.drop_column('apartments', 'price_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('price_history', postgresql.ARRAY(sa.DOUBLE_PRECISION(precision=53)), autoincrement=False, nullable=True))
    op.drop_table('price_history')
    # ### end Alembic commands ###
