"""added more fields to extract for apartments

Revision ID: 765360ebcbf7
Revises: 0dd05b94c536
Create Date: 2025-05-12 21:50:51.181063

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '765360ebcbf7'
down_revision: str | None = '0dd05b94c536'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('policies', sa.Text(), nullable=True))
    op.add_column('apartments', sa.Column('home_features', sa.Text(), nullable=True))
    op.add_column('apartments', sa.Column('ammenities', sa.Text(), nullable=True))
    op.add_column('apartments', sa.Column('price_history', sa.ARRAY(sa.Float()), nullable=True))
    op.add_column('apartments', sa.Column('similar_listings', sa.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'similar_listings')
    op.drop_column('apartments', 'price_history')
    op.drop_column('apartments', 'ammenities')
    op.drop_column('apartments', 'home_features')
    op.drop_column('apartments', 'policies')
    # ### end Alembic commands ###
