"""added_ai_summary_field

Revision ID: 84acdead0d66
Revises: 9f5ad1a3fa87
Create Date: 2025-05-18 11:09:17.614323

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '84acdead0d66'
down_revision: str | None = '9f5ad1a3fa87'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apartments', sa.Column('ai_summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apartments', 'ai_summary')
    # ### end Alembic commands ###
